version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.15.10
    container_name: gitea-server
    restart: always
    environment:
      - SSH_PORT=2222
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - DB_NAME=gitea
    networks:
      - gitea
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:3000"
      - "2222:2222"
    depends_on:
       - db

  db:
    image: postgres:13
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
